name: task_bell
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  alarm: ^4.0.10
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  numberpicker: ^2.1.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  permission_handler: ^11.3.1
  youtube_explode_dart: ^2.3.6
  path_provider: ^2.1.5
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
